### ISSUE TITLE
Tutorial help

### ISSUE THREAD

**Issue by NukerMaster** [andli/wipeusb#1]
Hi, 
apologize if i'm bothering you.
i came accross your project and i find it very useful. i'm on an internship and one of the project is to do exactly what you've done.
it's gonna come andy for our library. Also i liked your idea and proposed to my boss to buy those from blinkingstick.
i've got some issue, since i'm new in coding and scripting  ( i just passed my 1st year ), i woud like  to know is there's some thing else i got to change besides the "userhere" and "path" ?
best regards

**Comment by andli** [comment]
Hi, I think it's actually only `userhere` that has to be changed. It was a couple of years since i did one last time, so there may be dependencies that do not work. But please do a pull request if you find that something needs updating. :) Good luck!
